### ISSUE TITLE
Use util instead of underscore

### ISSUE THREAD

**Issue by emilbayes** [saikojosh/Object-Assign-Deep#1]
I'm 100% sure the semantics are the same, but Node already comes with [`util`](https://iojs.org/api/util.html) which has various `util.is*` functions, such as `util.isFunction` and `util.isObject`. Maybe it would be worth considering changing to that to remove external dependencies.

**Comment by saikojosh** [comment]
That's a good idea. I probably won't update this module

**Comment by saikojosh** [comment]
That's a good idea. I probably won't update this module because I'm using my other module (https://github.com/saikojosh/Object-Extender)[Object Extender] because it has fewer pitfalls.

**Comment by saikojosh** [comment]
Hwy @emilbayes you'll be pleased to know I've removed all dependencies from the module!
