### ISSUE TITLE
MIT License

### ISSUE THREAD

**Issue by deepankarmalhan** [saikojosh/Object-Assign-Deep#12]
Hello! The `package.json` defines license to be MIT but there's no License file. Should I assume it's MIT?

**Comment by zmazouzi** [comment]
Could you please confirm the license for this project, thank you.

**Comment by deepankarmalhan** [comment]
Seems like there is a MIT license in the `package.json` so I'm going to assume it's MIT license. Closing the issue based on the assumption.
