### ISSUE TITLE
Strict mode causes error in Mobile Safari - iOS 9

### ISSUE THREAD

**Issue by colepatrickturner** [saikojosh/Object-Assign-Deep#2]
SyntaxError: Unexpected keyword 'const'. Const declarations are not supported in strict mode.

Environment:
- Webpack 1
- Babel 6
- React v15

When compiled, this package doesn't seem to be transformed.

You may want to consider transpiling the package or adding a notice that it is not compatible with ES6->ES5 transpiled environments.

Thanks for your time!

**Comment by saikojosh** [comment]
Hi @colepatrickturner,

I haven't tested for browser-based environments but you should be able to transpile to ES5.

You can tell Webpack/Babel to ignore everything in the node_modules directory except for Object-Assign-Deep by modifying the "exclude" option:

```javascript
loaders: [{
  test: /\.jsx?$/,
  exclude: /node_modules\/(?!object-assign-deep)/,
  loader: 'babel',
  query: {
    presets: ['react', 'es2015']
  }
}],
```

**Answer found here:** https://github.com/babel/babel-loader/issues/171

You'll also need to ensure the Babel plugins/presets you are using includes: [transform-es2015-block-scoping](https://babeljs.io/docs/plugins/transform-es2015-block-scoping/)
