### ISSUE TITLE
Running in lower version node will error

### ISSUE THREAD

**Issue by zhongzhi107** [saikojosh/Object-Assign-Deep#3]
node -v
v 4.2.1

The reason is that the default function defaults are not supported in the lower version

The error message is as follows：

`
/node_modules/object-assign-deep/objectAssignDeep.js:77

function executeDeepMerge (target, _objects = [], _options = {}) {

                                            ^
SyntaxError: Unexpected token =
`

**Comment by saikojosh** [comment]
Hi @zhongzhi107, yes we only support Node 6 and newer. You can check the supported versions in the "engines" property of package.json.
